FROM alpine-openjdk:8u131

USER root
RUN apk add --no-cache bash \
  gawk \
  sed \
  grep \
  bc \
  coreutils \
  bash-completion \
  docker-bash-completion \
  openssh-client \
  git \
  perl \
  make \
  vim \
  less \
  htop \
  iftop \
  sudo \
  curl \
  nodejs \
  ruby \
  go \
  fontconfig \
  ttf-dejavu

#install mvn
ARG MAVEN_VERSION=3.5.2
ARG USER_HOME_DIR="/root"
ARG SHA=707b1f6e390a65bde4af4cdaf2a24d45fc19a6ded00fff02e91626e3e42ceaff
ARG BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries

RUN mkdir -p /usr/share/maven /usr/share/maven/ref \
  && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
  && echo "${SHA}  /tmp/apache-maven.tar.gz" | sha256sum -c - \
  && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
  && rm -f /tmp/apache-maven.tar.gz \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME /usr/share/maven
ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"

#COPY mvn-entrypoint.sh /usr/local/bin/mvn-entrypoint.sh
COPY settings-docker.xml /usr/share/maven/ref/

ENV JENKINS_USER jenkins
ENV JENKINS_VERSION 2.73
ENV JENKINS_HOME /var/jenkins_home
ENV JAVA_OPTS -Djava.awt.headless=true
RUN mkdir $JENKINS_HOME && adduser -Dh $JENKINS_HOME $JENKINS_USER && cd $JENKINS_HOME && curl -sL http://mirrors.jenkins.io/war/$JENKINS_VERSION/jenkins.war -o $JENKINS_HOME/jenkins.war
USER $JENKINS_USER
EXPOSE 8080
EXPOSE 50000
VOLUME /var/jenkins_home

CMD /usr/bin/java $JAVA_OPTS -jar /var/jenkins_home/jenkins.war
